### ISSUE TITLE
cozy-clis gives a TypeError

### ISSUE THREAD

**Issue by frallain** [cozy-labs/cozy-clis#4]
Hello, I just installed the CLI with:
```
sudo npm install cozy-clis -g
```
but I can't make it work:
```
 ✘  ~  cozy-clis  files list
Files stored in your Cozy Files
*******************************************************************************
/usr/lib/node_modules/cozy-clis/clis/files.js:19
        files = files.sort(function(file1, file2) {
                      ^

TypeError: files.sort is not a function
    at /usr/lib/node_modules/cozy-clis/clis/files.js:19:23
    at /usr/lib/node_modules/cozy-clis/clis/files.js:87:14
    at parseBody (/usr/lib/node_modules/cozy-clis/node_modules/request-json/main.js:26:12)
    at Request._callback (/usr/lib/node_modules/cozy-clis/node_modules/request-json/main.js:63:18)
    at Request.self.callback (/usr/lib/node_modules/cozy-clis/node_modules/request/index.js:148:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/cozy-clis/node_modules/request/index.js:876:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
 ✘  ~  node --version
v6.9.4
```

**Comment by ptbrowne** [comment]
Hi,

This repository is very old and not maintained (I was not aware of its existence BTW). It worked for Cozy V1, a different architecture from the current Cozy architecture. To import/export your data with your Cozy, we now use https://github.com/cozy/ach, tell me if it works for you :)

Thanks for reminding us that this repository exist, I am putting a deprecation notice on it ;)
